version: '3'
services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./db:/var/lib/mongo

  backend:
    image: ghcr.io/kobslbj/lab_requirements_management/backend:latest
    ports:
      - "5000:5000"
    environment:
        - MONGO_URI=mongodb://db:27017/lab_requirement_db
        - BACKEND_PORT=5000
        - JWT_KEY=secret
    depends_on:
      - db

  frontend:
    image: ghcr.io/kobslbj/lab_requirements_management/frontend:latest
    ports:
      - "3000:3000"
    environment:
        - name: NEXT_PUBLIC_API_URL
          value: "http://34.83.72.234:80/api"
        - name: API_URL
          value: "http://backend:80/api"
    depends_on:
      - backend