# Generated by Django 4.0.3 on 2022-12-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
