# Generated by Django 4.0.3 on 2022-12-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0002_alter_data_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='rate',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
