# Generated by Django 4.0.3 on 2022-12-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cellphone', '0003_delete_data_delete_rate_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('cellphone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_memory', models.FloatField(blank=True, null=True)),
                ('ram', models.FloatField(blank=True, null=True)),
                ('performance', models.FloatField(blank=True, null=True)),
                ('main_camera', models.FloatField(blank=True, null=True)),
                ('selfie_camera', models.FloatField(blank=True, null=True)),
                ('battery_size', models.FloatField(blank=True, null=True)),
                ('screen_size', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.FloatField(primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cellphone.users')),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
    ]
